version: "3.9"

services:
  handelingapi:
    image: harshit1001/handelingapi:1.0.1
    deploy:

      replicas: 3  

      restart_policy:
        condition: on-failure
    networks:
        - mynetwork
    ports: 
      - "8002:8002"
    env_file: healthcheck.env
  
  emailapi:
    image: harshit1001/emailapi:1.0.1
    deploy:

      replicas: 2
            
      restart_policy:
        condition: on-failure
    networks:
        - mynetwork
    ports: 
      - "8000:8000"

    env_file: healthcheck.env
  
  loginandsignupapi:
    image: harshit1001/loginandsignupapi:1.0.1
    deploy:

      replicas: 2
           
      restart_policy:
        condition: on-failure
    networks:
        - mynetwork
    ports: 
      - "8001:8001"
    env_file: healthcheck.env

  trigger:
    image: harshit1001/trigger:latest
    deploy:
      replicas: 1
      
      
      restart_policy:
        condition: on-failure
    networks:
        - mynetwork
    env_file: healthcheck.env
  
  db:
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: Harshit@1234
      MYSQL_DATABASE: healthcheck
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    deploy:
      replicas: 1
    ports: 
      - "3310:3306"

    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      retries: 10
    networks:
        - mynetwork

    env_file: healthcheck.env
networks:
  mynetwork:
    driver: overlay
volumes:
  dbdata:
